import "./globals.css"

import type { Metadata } from "next"
import { Header } from "@/components/common/header"
import localFont from "next/font/local"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const gilroyRegular = localFont({
  src: "../../public/fonts/gilroy/Gilroy_Regular.ttf",
  // weight: "400",
  display: "block",
  variable: "--font-gilroy-regular",
})

const gilroyMedium = localFont({
  src: "../../public/fonts/gilroy/Gilroy_Medium.ttf",
  // weight: "500",
  display: "block",
  variable: "--font-gilroy-medium",
})

const gilroySemiBold = localFont({
  src: "../../public/fonts/gilroy/Gilroy_Semibold.ttf",
  // weight: "600",
  display: "block",
  variable: "--font-gilroy-semibold",
})

const gilroyBold = localFont({
  src: "../../public/fonts/gilroy/Gilroy_Bold.ttf",
  // weight: "700",
  display: "block",
  variable: "--font-gilroy-bold",
})

const orange = localFont({
  src: "../../public/fonts/orange-squash/Orange_Squash_Demo.ttf",
  display: "block",
  variable: "--font-orange",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${gilroyRegular.variable} 
          ${gilroyMedium.variable} 
          ${gilroySemiBold.variable} 
          ${gilroyBold.variable}
          ${orange.variable}
      antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  )
}
